name: My First Action

on: [push]  

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
    - name: Print welcome message
      run: echo "Hello GitHub Actions! 🎉"
    
    - name: Print current date
      run: echo "The date is $(date)"
